name: Build and Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t my-simple-spa .

      - name: Extract static files
        run: |
          container_id=$(docker create my-simple-spa)
          docker cp $container_id:/usr/share/nginx/html ./output
          docker rm $container_id

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: ./output
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.nfp_uuycRERqJqfSh2o4fuCYM94Dd4boi5cD9442 }}
          NETLIFY_SITE_ID: ${{ secrets.42a10374-7b73-4dbe-bd49-5ad162588128 }}
